### ISSUE TITLE
[Feature request] Support react-native-tab-view 2.0.0-alpha

### ISSUE THREAD

**Issue by adongy** [react-navigation/react-navigation-tabs#100]
Currently, there is no way to get dynamic width tabs with createMaterialTopTabNavigator.

However, react-native-tab-view recently released an alpha to support that feature, check out
https://github.com/react-native-community/react-native-tab-view/pull/681

Can we release an alpha version of react-navigation + react-navigation-tabs to test this feature ?

Thanks.

**Comment by satya164** [comment]
Dynamic tab widths are still not supported in react-native-tab-view (PR welcome though). Also, it's alpha right now. `react-navigation-tabs` will be updated when it goes stable.

**Comment by adongy** [comment]
OK thanks!
