### ISSUE TITLE
Tabs created via createMaterialTopTabNavigator do not switch on click, but change when swiped

### ISSUE THREAD

**Issue by FibreFoX** [react-navigation/react-navigation-tabs#102]
### Current Behavior

- When having a tab navigation using `createMaterialTopTabNavigator()` only the first interaction with one tab does switch the content and the tab indicator. Any followed click on any unselected tab does not change anything. Swiping the content does work.
- Screencapture (sorry for the bad quality): 
![reactnavigationtabissue](https://user-images.githubusercontent.com/1042579/53433079-05958800-39f4-11e9-9557-b118879238eb.gif)

### Expected Behavior

- When clicking an inactive tab, the content changes and the indicator is adjusted accordingly.

### How to reproduce

- checkout the reproducable project: https://github.com/FibreFoX/react-navigation-tab-click-issue
- make sure to have a correct setup of Android SDK stuff (like a proper configured `local.properties` inside the android-folder)
- just run the example on the android emulator (or real-device, does not matter) via `react-native run-android`
- click both tabs, the second click does not result in changing the content

I used a release-candidate version of React Native, this might probably something which I totally have overlooked, or something with the new RN/React version.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.59.RC2
| node             | 10.2.1
| yarn      | 1.13.0

**Comment by FibreFoX** [comment]
I've checked the same code using current RN 0.58 (to be precise `0.58.5`), and it works, so this is a compatibility-issue with RN 0.59

**Comment by satya164** [comment]
can you add `"**/react-native-tab-view": "2.0.0-alpha.5",` under `resolution` field in your `package.json` and see if it still happens? https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by FibreFoX** [comment]
I had to add and link `react-native-reanimated`, but are hitting some weird error message using my example project:
![grafik](https://user-images.githubusercontent.com/1042579/53440389-b015a700-3a04-11e9-9fd0-413effacba1b.png)

Anything special I have to do to setup that new version?

**Comment by satya164** [comment]
Do you use a custom tab bar?

**Comment by satya164** [comment]
I'll take a look later on why this happens.

**Comment by FibreFoX** [comment]
Even being available in the linked repository, here the code I use to create my tabs:
```ts
class DefaultContent extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.tsx</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}

const AppNavigationContainer = createAppContainer(
	createMaterialTopTabNavigator({
		TabOne: {
			screen: DefaultContent
		},
		TabTwo: {
			screen: DefaultContent
		}
	})
);

interface Props {}
export default class App extends Component<Props> {
  render() {
    return (
      <AppNavigationContainer />
    );
  }
}
```

AFAIK nothing special or advanced.

**Comment by FibreFoX** [comment]
I might have found something: https://github.com/react-native-community/react-native-tab-view/blob/93edc9e130a63d16cd10b8c5b635e16fade8e7c5/src/PagerAndroid.js#L73

When adding `console.log`-lines, I can see that `this._isIdle` is `true` on the first click on one tab, but will always be `false` on any second click. After removing that part from the condition, it worked again.

I think there is some part missing, because it just will be set inside [`_handlePageScrollStateChanged`](https://github.com/react-native-community/react-native-tab-view/blob/93edc9e130a63d16cd10b8c5b635e16fade8e7c5/src/PagerAndroid.js#L91) and is always `false`, as `e` is not the correct expected thing.

**Comment by FibreFoX** [comment]
It seems that this `e` returns some wrapped event with newer ReactNative versions, therefor I could "fix" this at least for android (haven't checked iOS) using this [patch-package](https://www.npmjs.com/package/patch-package) file `react-native-tab-view+1.3.2.patch`:
```patch
diff --git a/node_modules/react-native-tab-view/src/PagerAndroid.js b/node_modules/react-native-tab-view/src/PagerAndroid.js
index 10f4552..70eb119 100644
--- a/node_modules/react-native-tab-view/src/PagerAndroid.js
+++ b/node_modules/react-native-tab-view/src/PagerAndroid.js
@@ -88,7 +88,7 @@ export default class PagerAndroid<T: *> extends React.Component<Props<T>> {
   };
 
   _handlePageScrollStateChanged = (e: PageScrollState) => {
-    this._isIdle = e === 'idle';
+    this._isIdle = e.nativeEvent.pageScrollState === 'idle';
 
     let nextIndex = this._currentIndex;
 
```

**Comment by FibreFoX** [comment]
@satya164 Is it worth do create some pull-request against the older `1.0`-Branch on that project? Or do you plan to replace that 1.x version of `react-native-tab-view` very soon?

**Comment by satya164** [comment]
@fibrefox I plan to release a new version by this weekend. But if you really need it earlier, you can create PR and I'll do a release.

**Comment by FibreFoX** [comment]
Right now I can live with my patch-file, so no rush needed, that fix/workaround does it's job 😸 I'm just glad I could find this thing, as it was kinda some show-stopper for using `react-navigation` for our tabs.

**Comment by schumannd** [comment]
I am experiencing a similar issue, where a jump form version 0.2.0 (RN 51) to 0.8.4 caused tabs not responding to taps anymore. Could this be related to this issue? If yes, is there already a version where this is fixed that I could try?

**Comment by FibreFoX** [comment]
@schumannd do you know [`patch-package`](https://www.npmjs.com/package/patch-package)? You can modify your local version inside the `node_modules`-folder, call `yarn patch-package react-native-tab-view` AFTER you checked and modified your own version in order to create the patch-file I posted above.

Maybe the issue is a different one, but using patch-package makes it faster, as you are not required to wait for a new release.

**Comment by satya164** [comment]
I released [2.0.0-alpha.0](https://github.com/react-navigation/react-navigation-tabs/releases/tag/v2.0.0-alpha.0) recently which shouldn't have this issue. Please give it a try and open a new issue if you still have the problem.

**Comment by FibreFoX** [comment]
@satya164 you mean I can change the dependency-resolution? As I'm not using this lib "directly", but haaving this due to react-navigation, ... do you have some kind of instruction for me here?

**Comment by satya164** [comment]
@FibreFoX you can use this lib directly. It should be a one line change for the import as react-navigation just re-exports it.

**Comment by kmraditya108** [comment]
I faced the same issue for fixes Kindly use the below:-

`const yourTab = createMaterialTopTabNavigator({
        screen_name_element: {
            screen: your_screen,
},{
        initialRouteName: "screen_name_element",
        tabBarPosition: 'top',
        animationEnabled: false,
        lazy: true,
        swipeEnabled:false,
}
})`

Use `animationEnabled: false,` that will help you.

**Comment by danniarreza** [comment]
@kmraditya108 yup, it works however, for a while. It only works as long as swipe function is being disabled or swipe gesture is not being performed, once the swipeEnabled is true and the swipe gestured is being performed the bug occurs again. I think not being able to swipe is kinda poor for UX isn't it?

Maybe there is any workable solution to this? I'm still having trouble following the solution that @FibreFoX  and @satya164 mentioned

**Comment by FibreFoX** [comment]
@danniarreza This issue is already fixed, you might want to update your lockfile, as a fixed version gets provided with up2date version of `react-navigation`. Please keep in mind, that this patch-file was ment for RN 0.59 and above, the fixed version supportes backward-compatibility.

**Comment by danniarreza** [comment]
@FibreFoX you mean to update the root folder package-lock.json file? Could u elaborate more how to update it, or which part should I change?

**Comment by FibreFoX** [comment]
@danniarreza One quick way would be to delete that lock-file and run `npm install` again (I'm using yarn instead of npm). Just make sure to have the latest dependency-versions inside your `package.json` regarding the navigation-deps.

**Comment by satya164** [comment]
Try `yarn remove react-navigation && yarn add react-navigation`

**Comment by danniarreza** [comment]
@FibreFoX Unfortunately I'm still stuck at react-native-gesture-handler installation, it says no such file in MainApplication.js whereas I already tried to follow the instructions here https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html and already imported this

![image](https://user-images.githubusercontent.com/30825334/55406116-ae9c4900-5585-11e9-8810-1397c2166740.png)

Am I missing something?

**Comment by danniarreza** [comment]
@satya164 it implies that I have to install the latest version of react-navigation then?

**Comment by FibreFoX** [comment]
@danniarreza hm, I think this is out-of-scope of this issue regarding the integration of the `react-native-gesture-handler`, as that gets downloaded via NPM/YARN due to `react-navigation`, you might not need to add that dependency itself.

The original issue for me was that using some older version of `react-navigation` included that old version of `react-native-tab-view` , so you need to use a newer version of `react-navigation` in order to get the fixed versions.

**Comment by danniarreza** [comment]
Hey guys, just to inform that after updating my project's react-navigation from @2.0.1 to the latest @3.6.0 I believe, my problem about not being able to switch screen on click is already being solved. Thank you so much! Using the latest react-native @0.59 also.

**Comment by schumannd** [comment]
Just a side note: our similar problem (tabs not responding to taps anymore) was caused by an update changing the way `tabBarOnPress` works. Before the default handler was always called, after it was not.

**Comment by danniarreza** [comment]
I see, nice to have a supporting community btw.

**Comment by gusgard** [comment]
I fix it using the following line 
```
"resolutions": {
    "react-native-tab-view": "0.0.78"
  },
```
with version `"react-navigation": "1.5.12"`

NOTE: `resolution` only works with `yarn.lock`, if you have `package.lock` I think you need to use `npm shrinkwrap`

**Comment by matwming** [comment]
You can use react-navigation 3.11.0. It does not have this problem.

**Comment by jordy-wijman** [comment]
> Hi @FibreFoX , I faced the same issue for fixes Kindly use the below:-
> 
> `const yourTab = createMaterialTopTabNavigator({ screen_name_element: { screen: your_screen, },{ initialRouteName: "screen_name_element", tabBarPosition: 'top', animationEnabled: false, lazy: true, swipeEnabled:false, } })`
> 
> Use `animationEnabled: false,` that will help you.

This indeed was the solution, now in react-navigation-tabs they removed this `animationEnabled: false`... how do we disable the animation now.. there is no alternative.

**Comment by RahulNainwal** [comment]
i am getting the same issue, no any solution working for me:
"react": "16.8.3",
"react-native": "0.59.9",
"react-navigation": "^3.12.1",

**Comment by bonellicious** [comment]
+1
