### ISSUE TITLE
Importing and using the library

### ISSUE THREAD

**Issue by nwaughachukwuma** [react-navigation/react-navigation-tabs#106]
Hi @satya164 In the example shown on the main page, I see you imported the bottom tab navigator from react-navigation `import { createBottomTabNavigator } from ‘react-navigation’` Is there a reason for this? Why not from react-navigation-tabs?

**Comment by brentvatne** [comment]
you can import from react-navigation-tabs also, but react-navigation bundles react-navigation-tabs and re-exports it for convenience and because that's what it did before we split this out into a separate library.

**Comment by nwaughachukwuma** [comment]
Alright @brentvatne thanks for the update
