### ISSUE TITLE
setting tabBarOnPress causes defaultHandler to not be called

### ISSUE THREAD

**Issue by schumannd** [react-navigation/react-navigation-tabs#107]
### Current behaviour

when settings tabBarOnPress e.g.:

``` 
  createBottomTabNavigator(
    {
            Training: {
              screen: TrainingStack,
              navigationOptions: {
                tabBarAccessibilityLabel: LABEL,
                tabBarLabel: 'Training',
                tabBarIcon: tabBarIcon(img),
                tabBarOnPress: () => doSomethignElse(),
              },
            },
...
```

the default handler does not get called, i.e. the tab does not activate when tapped. (see [these 5 lines](https://github.com/react-navigation/react-navigation-tabs/blob/e23142ec736cf7516123e2f9ba96f102045aae85/src/utils/createTabNavigator.js#L125))

### Expected behaviour
Despite setting tabBarOnPress I would expect the tab to still work normally (as [described here](https://reactnavigation.org/docs/en/tab-navigator.html#tabbaronpress))

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 59.6
| react-navigation-tabs | 1.0.2
| node                  | 9.8.0
| npm or yarn           | 6.0.0

**Comment by satya164** [comment]
You need to call default handler yourself. This allows you to override default behavior.

**Comment by schumannd** [comment]
Then I would add that explicitly to the docs.

**Comment by brentvatne** [comment]
@schumannd - you should!
