### ISSUE TITLE
activeTintColor has no effect on createMaterialBottomTabNavigator

### ISSUE THREAD

**Issue by dulmandakh** [react-navigation/react-navigation-tabs#14]
When you set activeTintColor when creating tab navigator with createMaterialBottomTabNavigator, it has no effect, but uses default color

tabBarOptions: {
    activeTintColor: 'green'
}

### Current behaviour

- tab label color is rgba(0, 0, 0, 0.5)

### Expected behaviour

- tab label color must be activeTintColor

### What have you tried

createBottomTabNavigator works just fine uses specified color

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.55.3
| react-navigation-tabs | 0.1.0-alpha.6
| node                  | 9.11.1
| yarn           | 1.6.0

**Comment by brentvatne** [comment]
cc @satya164 ^

**Comment by SharkyLV** [comment]
Is it me or MaterialBottomTabNavigator is not stylable? I am not able to set a background colour or apply shadows...

**Comment by rjatin007** [comment]
Same here  @SharkyLV  MaterialBottomTabNavigator is not stylable.

**Comment by satya164** [comment]
`createMaterialBottomTabNavigator` doesn't have a `tabBarOptions` config. You can put `activeTintColor` and `inactiveTintColor` outside and it'll work as expected: https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#materialbottomtabnavigatorconfig

**Comment by sfreeman28** [comment]
Thanks for the clarification @satya164. It seems that the documentation you linked has an error as it has an example which uses tabBarOptions to set the activeTintColor:
```
tabBarOptions: {
  activeTintColor: '#e91e63',
  labelStyle: {
    fontSize: 12,
  },
  style: {
    backgroundColor: 'blue',
  },
}
```

@SharkyLV I got the background color changing by using https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#tabbarcolor
eg
```
navigationOptions: ({ navigation }) => ({
	tabBarColor: '#FAFAFA'
}),
```
hope that helps

**Comment by arled** [comment]
How do you not show the label with createMaterialBottomTabNavigator?

**Comment by sfreeman28** [comment]
> How do you not show the label with createMaterialBottomTabNavigator?

Try setting `labeled: false` in your tab config.

**Comment by rafidamr** [comment]
> I got this working by pulling it out of the tabBarOptions tag
> 
> ```
> const Tabs = createMaterialBottomTabNavigator(
> 	{
> 		CollectionList: CollectionStack,
> 		Settings: SettingsStack,
> 	},
> 	{
> 		initialRouteName: 'CollectionList',
> 		activeTintColor: '#000000',
> 		inactiveTintColor: '#8E8E93',
> 	})
> ```

Thanks. In my case, by pulling out the same way does work for `activeTintColor` but for `inactiveTintColor` it should be nested in `tabBarOptions`
