### ISSUE TITLE
Bottom tab bars and keyboard on Android

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation-tabs#16]
### Current behaviour

Keyboard pushes tab bar up on Android when open.

### Expected behaviour

By default, the tab bar should be hidden when the keyboard is open. It should be controllable with tab bar options.

### Code sample & screenshots

Examples and screenshots in original issue: https://github.com/react-navigation/react-navigation/issues/618

### What have you tried

Many examples listed in original issue

**Comment by ImBeCiliC** [comment]
How's the progress on this Issue related to React-Navigator v2. Are there only Workarounds for v1?

**Comment by fierysolid** [comment]
@export-mike great solution. I would add a check to make sure `this.keyboardEventListeners` is defined before trying to call `forEach` in `componentWillUnmount`

**Comment by FakhruddinAbdi** [comment]
Could pleases some one let me know whats `navbar component` 
Is it the custom component passed to the tabNavigator like this:
`tabBarComponent: TabBarBottom,` ?

**Comment by hegelstad** [comment]
@FakhruddinAbdi 
```
class TabBarComponent extends React.Component {
  state = {
    visible: true
  }

  componentDidMount() {
    if (Platform.OS === 'android') {
      this.keyboardEventListeners = [
        Keyboard.addListener('keyboardDidShow', this.visible(false)),
        Keyboard.addListener('keyboardDidHide', this.visible(true))
      ];
    }
  }

  componentWillUnmount() {
    this.keyboardEventListeners && this.keyboardEventListeners.forEach((eventListener) => eventListener.remove());
  }

  visible = visible => () => this.setState({visible});

  render() {
    if (!this.state.visible) {
      return null;
    } else {
      return (
        <BottomTabBar {...this.props} />
      );
    }
  }
}
```

**Comment by guliash** [comment]
Has anyone achieved the desired behavior using createMaterialBottomTabNavigator?

**Comment by ploureiro** [comment]
Another working solution is to set the _android:windowSoftInputMode_ in **AndroidManifest.xml**: 
` <activity
        android:name=".MainActivity"
        android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize">`

works like a charm! ️🎉

**Comment by Arjan-Zuidema** [comment]
> Another working solution is to set the _android:windowSoftInputMode_ in **AndroidManifest.xml**:
> `<activity android:name=".MainActivity" android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize">`
> 
> works like a charm! ️🎉

This workaround does not work well in combination with [KeyboardAvoidingView](https://facebook.github.io/react-native/docs/keyboardavoidingview). A better solution would be to hide the tabbar when the keyboard is visible which is also not perfect.

**Comment by hegelstad** [comment]
Make your own minimal ‘.ts.d’, the official package doesn’t have any declaration.

**Comment by v-ken** [comment]
If you're having issues with KeyboardAvoidingView when using @ploureiro's solution, try using `android:windowSoftInputMode="adjustPan"` instead.

```
<activity android:name=".MainActivity" android:windowSoftInputMode="adjustPan">
```

**Comment by thisiswhale** [comment]
TabBarBottom is deprecated.

**Comment by AurangzaibRamzan** [comment]
@v-ken thanks its work like gem for me

**Comment by brentvatne** [comment]
@satya164 has been working on https://github.com/callstack/react-native-paper/pull/680 for material bottom tabs, hopefully we'll have something similar for normal bottom tabs soon

**Comment by renato-bvdash** [comment]
is there any solution to this yet?  @hegelstad 's solution isn't working for me; the keyboard still pushes the bottom tab bar up.

**Comment by marlosirapuan** [comment]
> If you're having issues with KeyboardAvoidingView when using @ploureiro's solution, try using `android:windowSoftInputMode="adjustPan"` instead.
> 
> ```
> <activity android:name=".MainActivity" android:windowSoftInputMode="adjustPan">
> ```

thank you!

**Comment by tatasfachrul** [comment]
> If you're having issues with KeyboardAvoidingView when using @ploureiro's solution, try using `android:windowSoftInputMode="adjustPan"` instead.
> 
> ```
> <activity android:name=".MainActivity" android:windowSoftInputMode="adjustPan">
> ```

This works fine for me! Thanks man

**Comment by smitthakkar1** [comment]
Facing same problem and I tried many solutions all from github issues and stackoverflow but none of them working 😞

**Comment by bobber205** [comment]
@smitthakkar1 Did you try the adjustPan solution? What did you try that didn't work? I just did adjustPan and it's working well with KeyboardAvoidingView.

**Comment by smitthakkar1** [comment]
Yeah I figured out what the issues was. I rebuild the android app and it worked. 👍 
thanks for follow up 😄

**Comment by gamingumar** [comment]
How to scroll to the focused input? This automatically works in iOS. Is there some builtin solution to handle this or i have to implement scroll to that input position manually?

**Comment by maxaggedon** [comment]
@gamingumar I think this is what you are looking for : [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view)

**Comment by brentvatne** [comment]
@satya164 - maybe we can backport 2a1d753 to the latest pre-2.0 release and make the default value `false` so it's not a breaking change

**Comment by satya164** [comment]
@brentvatne okay, I'll do it

**Comment by AbdelrahmanNabil96** [comment]
I still have this issue with version 3.x, any solutions ?
P.S i use Expo, so i can't use the androidmanifest.xml file solution

**Comment by c316** [comment]
I'm still having this issue on `"react-navigation": "3.8.0",` which seems to be installing the `react-navigation-tabs` `"version": "1.1.2"`

Here is my MainTabNavigator

```
export default createBottomTabNavigator(
  {
    HomeStack,
  },
  {
    keyboardHidesTabBar: true,
  }
);
```

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!

**Comment by brentvatne** [comment]
oh i noticed what is wrong there

```js
export default createBottomTabNavigator(
  {
    HomeStack,
  },
  {
    tabBarOptions: {
      keyboardHidesTabBar: true,
    }
  }
);
```

please submit a pr to add this under `tabBarOptions` on https://reactnavigation.org/docs/en/bottom-tab-navigator.html#bottomtabnavigatorconfig :) https://github.com/react-navigation/website
