### ISSUE TITLE
Add lazy option for createBottomTabNavigator

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation-tabs#23]
We should support disabling "lazy" if people want to. See: https://github.com/react-navigation/react-navigation/issues/4254

**Comment by karanmartian** [comment]
now that the commit is made, will the lazy option be available with a new release?

**Comment by djendacott** [comment]
Any update on this? Lazy being forced to true is making tab navigation too slow.

**Comment by satya164** [comment]
> Any update on this? Lazy being forced to true is making tab navigation too slow.

It's already released. Also `lazy` should make it fast since only 1 tab is rendered on startup, not slow. You're probably seeing this, which is a separate issue: https://github.com/react-navigation/react-navigation/issues/4412

**Comment by djendacott** [comment]
@satya164 Are you certain this is released? I believe createBottomTabNavigator does not allow the option to set lazy to false (preload all tabs).

As our tab content is quite heavy, I'm currently seeing no solution but to remain with the deprecated tabNavigator purely so we can disable lazy.

**Comment by FreshBreadLux** [comment]
Has this change been released yet? I don't see anything in the documentation about being able to set lazy to false with createBottomTabNavigator. I'd like to be able to update from TabNavigator to createBottomTabNavigator, but need to disable lazy loading.

**Comment by brentvatne** [comment]
It has been released, docs need to be updated
