### ISSUE TITLE
jumpToIndex deprecation warning

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation-tabs#36]
Have to do this to avoid the warning currently: https://github.com/react-navigation/react-navigation/blob/c518e7f36c653d8298ae6d80564a92685995e2d2/examples/NavigationPlayground/js/StacksOverTopTabs.js#L86

**Comment by brentvatne** [comment]
tracked here https://github.com/react-navigation/react-navigation/issues/4878

**Comment by grvk** [comment]
I'm seeing same issue when I'm trying to use a 'createTabNavigator'
TabBarTop.js has a number of jumpToIndex calls

**Comment by satya164** [comment]
Closing since `jumpToIndex` was removed long back.
