### ISSUE TITLE
Please adding swipeEnabled and animationEnabled BACK in BottomTabNavigator!!!

### ISSUE THREAD

**Issue by HessiPard** [react-navigation/react-navigation-tabs#43]

**Comment by fantasy525** [comment]
I need this, too,but Do you have any other ideas?

**Comment by satya164** [comment]
Both the Android and iOS design guidelines discourage swipe on bottom tabs. It's also extremely uncommon among any apps you try. I have never seen swipeable tabs for the bottom tabs. Users don't expect it.

You shouldn't be adding a swipe gesture for bottom tabs if you want to provide a consistent UX. You can still build swipeable bottom tabs using the `tabBarPosition` prop of `MatereialtoptabNavigator`, though that won't provide the best UX.
