### ISSUE TITLE
NavigationEvents: onWillBlur/onDidBlur events not fired

### ISSUE THREAD

**Issue by n1ru4l** [react-navigation/react-navigation-tabs#55]
### Current behaviour

When mounting the following component in one of my tabs the `onWillBlur` and `onDidBlur` handlers are not called.

### Expected behaviour

The `onWillBlur` and `onDidBlur` handlers should be called when navigating to another tab.

### Code sample

```js
<NavigationEvents
  onWillFocus={payload => console.log('ASD129', 'will focus', payload)}
  onDidFocus={payload => console.log('ASD129', 'did focus', payload)}
  onWillBlur={payload => console.log('ASD129', 'will blur', payload)}
  onDidBlur={payload => console.log('ASD129', 'did blur', payload)}
/>
```

### Screenshots (if applicable)

**Not available**

### What have you tried

- I tried to search the issues for a bug report
- I tried to search the pull requests for an pending fix

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 12
| react-native          | 0.56.0
| react-navigation-tabs | 0.8.2
| node                  | v8.11.3
| npm or yarn           | 1.7.0

**Comment by n1ru4l** [comment]
I could not reproduce this issue with expo: https://snack.expo.io/@n1ru4l/reproduction-react-navigation-tabs-issue-55

So it must be something else inside my application. I am going to close this issue until I have further information.

**Comment by andelar** [comment]
I have the same weird behaviour. Did you figure it out?

Actually onWillBlur fires usually, but not consistently, for example if exiting shortly after entering the screen, which means some cleanup code cannot be relied on to run.
onDidBlur seemingly never fires. I'm sure it's something I've done but I can't figure out. Very strange.

**Comment by BashrO** [comment]
same in here, onWillBlur/onDidBlur doesn't called.

**Comment by n1ru4l** [comment]
@andelar @BashrO using `this.props.navigation.addListener` worked. However I still could not reproduce this issue in a new app. Would be awesome if you could try it too!
