### ISSUE TITLE
tabBarOnPress should include the pressed route

### ISSUE THREAD

**Issue by theluk** [react-navigation/react-navigation-tabs#60]
Hello,

currently the tabBarOnPress includes only the navigation and defaultHandler, but does not include the most important information: the pressed route. 

https://github.com/react-navigation/react-navigation-tabs/blob/e8c646ee19080026828fde137ee1519eb02a47f3/src/utils/createTabNavigator.js#L138

**Comment by brentvatne** [comment]
`tabBarOnPress` is defined on each screen in `navigationOptions` so you know what the route is from there, it's in `navigation.state` - https://snack.expo.io/@notbrent/intelligent-bagel

**Comment by theluk** [comment]
That is not true.
It is not I in the state yet because it was not dispatched yet at this
moment. It's dispatched after the default Handler is called.

Brent Vatne <notifications@github.com> schrieb am Fr., 19. Okt. 2018, 20:22:

**Comment by brentvatne** [comment]
did you look at the example? it alerts the active route
