### ISSUE TITLE
Scroll position?

### ISSUE THREAD

**Issue by Jonovono** [react-navigation/react-navigation-tabs#62]
Hi. One thing I would like to do is in my custom tab bar component get access to the scroll position as a user is swiping between tabs so that I can have an animation in my tab bar component that animates with you as you scroll. Is this possible?

Thanks!

**Comment by satya164** [comment]
You get a `position` prop which you can use to do that.

**Comment by satya164** [comment]
https://snack.expo.io/@satya164/react-navigation-custom-tabbar-example

**Comment by Jonovono** [comment]
Oh, amazing, thanks :)

**Comment by humbkr** [comment]
Hello,
I'm using react-navigation 4.x with react-navigation-tabs.
It seems the API has changed and **position** is now an instance of AnimatedCond from react-native-reanimated lib, and so the provided snack is no longer working.

I'm a beginner regarding animations and I can't figure out how to use **position** to animate my custom header, could someone provide a snack that works with the latest version?

Thanks!

**Comment by satya164** [comment]
I have updated the snack.

**Comment by humbkr** [comment]
Thank you!

**Comment by michaelkoelewijn** [comment]
Is it possible to get this position value outside of the tabbar as well?
I want to animate an image across my app based on the routes
