### ISSUE TITLE
Update dependency react-native-tab-view to 1.2.0

### ISSUE THREAD

**Issue by JensDebergh** [react-navigation/react-navigation-tabs#65]
### Current behaviour

React-navigation-tabs is running an "outdated" version of react-native-tab-view.

### Expected behaviour

React-navigation-tabs should use the latest version `1.2.0` since this version includes numerous patches as well as proper RTL support.

### Code sample

react-navigation-tabs: https://github.com/react-navigation/react-navigation-tabs/blob/master/package.json#L46

react-native-tab-view: https://github.com/react-native-community/react-native-tab-view/blob/master/package.json#L3

**Comment by brentvatne** [comment]
@satya164 - is this straightforward to do?

**Comment by satya164** [comment]
@brentvatne yeah, it follows semver so will be straightforward. though maybe i should do a new release with after merging some PRs first.

**Comment by JensDebergh** [comment]
I can try to create a pull request with the updated packages tonight if you'd like.

Let me know where I can help.

**Comment by satya164** [comment]
@JensDebergh thank you. I'll do a new release later today.

**Comment by JensDebergh** [comment]
Thanks @satya164!

**Comment by brentvatne** [comment]
@JensDebergh @satya164 - either of you want to update this dep now?

**Comment by JensDebergh** [comment]
@brentvatne

We tried upgrading `react-navigation` to  `Release 3.0.0-rc.5` which includes the new release of `react-navigation-tabs`. 

But it seems something is broken on the new RC of `react-navigation` unrelated to react-navigation-tabs.

```
error: bundling failed: Error: Unable to resolve module `react-native-gesture-handler` from `/Users/Projects/node_modules/@react-navigation/native/src/Scrollables.js`: Module `react-native-gesture-handler` does not exist in the Haste module map
```

We cleared `node_modules` to see if this would fix the issue but nothing helps.

Can you point us in the right direction on this one? We would be happy fix up a patch on `react-navigation`

**Comment by brentvatne** [comment]
did you install react native gesture handler in your project?

**Comment by JensDebergh** [comment]
@brentvatne We didn't install `react-native-gesture-handler` manually. Since it is a peer dependency of react-navigation.
