### ISSUE TITLE
Labels overlapping icon on IPAD when using createBottomTabNavigator

### ISSUE THREAD

**Issue by proutek** [react-navigation/react-navigation-tabs#68]
### Current behaviour

Labels are overlapping icons on IPAD if tabBarLabel is function returning **\<Text\>Label\</Text\>** and not just string in navigationOptions
According to documentation it should be supported

[https://reactnavigation.org/docs/en/bottom-tab-navigator.html](https://reactnavigation.org/docs/en/bottom-tab-navigator.html)
**tabBarLabel**
Title string of a tab displayed in the tab bar or React Element or a function that given { focused: boolean, tintColor: string } returns a React.Node, to display in tab bar. When undefined, scene title is used. To hide, see tabBarOptions.showLabel in the previous section.

### Expected behaviour

Labels do not overlap icons.
### Code sample

Expo snack (Run it on **IPAD**)
[https://snack.expo.io/@chilly/vigorous-kiwi](https://snack.expo.io/@chilly/vigorous-kiwi)

It can be reproduced also on android tablet or phone when I modify this function in 
**node_modules\react-navigation-tabs\src\views\BottomTabBar.js**

```
  _shouldUseHorizontalLabels = () => {
    return true; 
}
```

### Screenshots (if applicable)

Android tablet (with modified BottomTabBar.js)
![screenshot_2018-11-07-10-14-44](https://user-images.githubusercontent.com/21219132/48129031-994a1980-e288-11e8-92f6-995677a2877f.png)

IPAD
![ipad](https://user-images.githubusercontent.com/21219132/48129216-15446180-e289-11e8-8b1e-f21c7a97818f.jpg)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs | 0.8.4
| node                  |
| npm or yarn           |

**Comment by brentvatne** [comment]
you should not use a text component for the label, you should just use text.

`tabBarLabel: () => <Text>Home</Text>` should be `tabBarLabel: Home`. if you set it to your own text component then we assume you will choose the styles that work for you.

**Comment by brentvatne** [comment]
also you can set the size of the icon when it's displayed in horizontal mode using the horizontal property that's passed in to tabBarIcon - https://snack.expo.io/@notbrent/vigorous-kiwi

**Comment by proutek** [comment]
Well I need label to be dynamic because it's translated and language can be switched in the app. I need also different styling (not just font color but also font family and size) but I guess I hopefully achieve that with labelStyle.

**Comment by proutek** [comment]
It could be nice to be able to disable this horizontal functionality.

**Comment by brentvatne** [comment]
you can customize the language with screenProps

```
navigationOptions: ({ screenProps }) => ({
  tabBarLabel: screenProps.language === 'en' ? 'Hello' : 'Hola',
});
```

you can customize the styling with the label style

```
createTabNavigator({ ..routes }, {
  tabBarOptions: {
    labelStyle: {},
  },
});
```

if you want to add support for disabling automatic horizontal mode please open a pr here. it doesn't seem super desirable though tbh because this behavior is expected on ipad and landscape on iphone.  it might be easier for you to just create your own bottom tab navigator, it's meant to be very easy to do this, see https://github.com/react-navigation/react-navigation-tabs/blob/master/src/navigators/createBottomTabNavigator.js. or you could just swap in your own tab bar component
