### ISSUE TITLE
You can't navigate back from last tab to first on iOS, if the tab has auto width

### ISSUE THREAD

**Issue by Xyzor** [react-navigation/react-navigation-tabs#73]
### Current Behavior

When I give a `width: 'auto'` or `width: null, flex: 1` to the tabStyle, I can't navigate back from last page if there is not enough tab to overflow the screen.

### Expected Behavior

Either to be able to scroll the tabbar or to not move the selected tab item to the left side of the screen like on android.

### How to reproduce

In the [demo](https://snack.expo.io/@fitsolutionskft/basic-tab-v2-ios-bug), on iOS select the `Settings2` menu and try to navigate back to `Home` menu.  
A device which is big enough either on portrait or landscape to show all tabs.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.2
| react-native     | 0.57
| node             |  10.13.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
@satya164 - not sure what the expected behavior is for top tabs or if this is supported. @Xyzor it might be helpful if you share a mockup or description of what you're trying to accomplish

**Comment by Xyzor** [comment]
My main goal is to use `flex: 1` on `tabStyle`, instead of fixed width, because with fixed width the tab's label either break into new lines or some tabs are unnecessarily wide.

On android the demo is working because when i select a tab, it doesn't move to the left.

**Comment by satya164** [comment]
The width depends on the width of the tab bar. Dynamic width for the tab items is not supported because it's every complicated to implement. I'm not sure what you're trying to achieve, but you probably need to customize the tab bar itself or use a custom tab bar.

**Comment by Xyzor** [comment]
@satya164 Thanks for the info.
