### ISSUE TITLE
Inconsistent state with createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by brunoandradebr** [react-navigation/react-navigation-tabs#77]
So you asked me to create an example, even this bug been a default initialization (core bug), here it's : https://snack.expo.io/HyBuGWJeE

Tap about, waits to transition end, then tap on about again, then SWIPE back to home, once you're there, try to tap about again, nothing happens, like on swipe it's not updating active flag. 

It's why I didn't create an example, it's a default initialization.

**Comment by jpshelley** [comment]
Its hard to fully understand the issue description, but I believe we are seeing the same thing.

1. We will navigate to Screen A
2. When we try to navigate to Screen B, the navigation.state says its already on that specific state. Therefore we cannot navigate to Screen B

**Comment by brentvatne** [comment]
try out https://github.com/react-navigation/react-navigation-tabs/releases/tag/v2.0.0-alpha.0 - note however that it requires react-native-reanimated is installed (included in expo managed workflow by default but in a bare react native app you will need to install/link)

**Comment by satya164** [comment]
It should be impossible to reach an inconsistent state with the 2.0.0-alpha.0. So, I'm closing this issue. If you still face this issue, please create a new issue  with repro :)

**Comment by jpshelley** [comment]
We found out it only happened when we had animated set to true, so we're disabling it for now. Still on nav v2. Once we upgrade to v3 we'll look into the new tabs as well. Thanks all!
