### ISSUE TITLE
Hidden tab container gets re-rendered when lazy=true

### ISSUE THREAD

**Issue by Morriz** [react-navigation/react-navigation-tabs#79]
### Current behaviour

A tab with `lazy = true` that was previously visited gets re-rendered in the background when it is hidden and conditions changed that should make it re-render if `lazy` would have been `true`

This is a separate issue from 
https://github.com/react-navigation/react-navigation-tabs/issues/78 as that initially started about the Modal, but if you feel like closing that one and continuing here, that might be even better as the core issue is reported here.

### Expected behaviour

No action happening in the hidden tab

### Code sample

https://snack.expo.io/@morriz/tab-issues:-hidden-tab-container-gets-re-rendered-when-lazy=true

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 9 (qemu emulator)
| react-native          | expo 31
| react-navigation-tabs | 1.0.1
| node                  | 11.2
| npm or yarn           | npm 6.4.1

**Comment by Morriz** [comment]
removing this as it's not reproducible, and the other issue is not related

**Comment by Morriz** [comment]
I updated the snack to make it very clear.

**Comment by Morriz** [comment]
@brentvatne I have located the exact issue in the above snack, and would like to know what you think

**Comment by brentvatne** [comment]
you seem confused about what lazy does. it does not unmount components when you switch away, it just lazy loads them, so the component is not mounted until you switch to it for the first time.

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation.github.io/issues/324 as follow up since this is probably not clear enough in the docs

**Comment by fbartho** [comment]
@morriz, you might enjoy the withNavigationFocus helper. That will let you decide not to render the modal just because your screen is being rendered “in the background”

**Comment by Morriz** [comment]
@brentvatne I understand that it does not get dismounted. I just thought that 'lazy' views out of sight would not be active at all. Maybe old remnants of dom tree memories. 
But thanks @fbartho, I did manage to disable based on `willBlur` already. Might be using the same stuff.
