### ISSUE TITLE
tab issues: back button icon gone after upgrading react-native

### ISSUE THREAD

**Issue by Morriz** [react-navigation/react-navigation-tabs#82]
### Current behaviour

After upgrading react-native to another version, the back button disappears after `expo publish`. It does take up the space and responds to touch and behaves as it should. It's just not visible any more.

### Expected behaviour

The back button to be visible.

### Code sample

https://snack.expo.io/@morriz/tab-issues-back-button-icon-gone-after-upgrading-react-native

### What have you tried

1. `expo publish`
2. upgrade react-native to another version
3. `expo publish`
4. open LeftTab and press TOUCH ME RIGHT HERE

### Your Environment

software | version
-- | --
ios or android | both
react-native | expo@31.0
react-navigation-tabs | 1.0.1
node | 11.2
npm | 6.4.1

**Comment by Morriz** [comment]
This problem has cost me quite some time to deal with, and it prevents us from upgrading RN after ejecting. Which is sad.

While publishing I noticed that expo-cli mentioned:
```
We noticed you did not build a standalone app with this SDK version and release channel before. Remember that OTA updates will not work with the app built with different SDK version and/or release channel.
```
But I don't think that has to do with this. Maybe it does in a way I don't understand? Everything else seems to be working, which makes this bug strange.

I will probably get a response to this like "don't upgrade RN as it might create unforeseen side effects"? If so, this can be closed and left as reference. But I feel something can be done about this, as up till now it's the only problem I found after upgrading...

**Comment by satya164** [comment]
Closing this since it doesn't seem like related to this library. If you disagree, feel free to open a new issue.

**Comment by hasanzia1993** [comment]
> This problem has cost me quite some time to deal with, and it prevents us from upgrading RN after ejecting. Which is sad.
> 
> While publishing I noticed that expo-cli mentioned:
> 
> ```
> We noticed you did not build a standalone app with this SDK version and release channel before. Remember that OTA updates will not work with the app built with different SDK version and/or release channel.
> ```
> 
> But I don't think that has to do with this. Maybe it does in a way I don't understand? Everything else seems to be working, which makes this bug strange.
> 
> I will probably get a response to this like "don't upgrade RN as it might create unforeseen side effects"? If so, this can be closed and left as reference. But I feel something can be done about this, as up till now it's the only problem I found after upgrading...

I have the same issue, any fix ?

**Comment by brentvatne** [comment]
@hasanzia1993 - post more info to https://forums.expo.io please!
