### ISSUE TITLE
Does this work on web?

### ISSUE THREAD

**Issue by sirpy** [react-navigation/react-navigation-tabs#92]
Does this work on web?

**Comment by satya164** [comment]
Unfortunately not. We use `react-native-reanimated` which doesn't work on web.

**Comment by tehOPEologist** [comment]
is there any thoughts on making this part of the react-navigation ecosystem web-compatible?  i definitely think there's a need to make all of react-navigation web-compatible to increase the multi-platform deployment strategies with react-native applications.  i know expo has experimental support for react-navigation on the web, but i'm not sure if that includes the tab navigators as well (i would assume it does somehow?).  regardless, i think there's definitely a need for web compatibility and wonder what the current progress (if any) there is towards making all of react-navigation, including this package specifically, web compatible.  thanks!
