### ISSUE TITLE
ScrollView is not working with createMaterialTopTabNavigator in Android

### ISSUE THREAD

**Issue by billouboq** [react-navigation/react-navigation-tabs#95]
@listingzhao explained the problem pretty well in his post.

See :

https://github.com/react-navigation/react-navigation/issues/4987#issue-359859427

**Comment by vractal** [comment]
I'm having the same problem, any news on it @billouboq?

**Comment by billouboq** [comment]
@vractal ended up using react-native-tab-view and doing tabs computation with my own state : 
Can't show code of it but you change tab index just change your route parameters.
In your constructor check route parameters to know which tab you want to load and that's it.

See : https://github.com/react-native-community/react-native-tab-view/tree/master/example

**Comment by satya164** [comment]
I think this issue is fixed in latest react-navigation-tabs. You'll need to use `ScrollView` from `react-native-gesture-handler`. Please open a new issue if you still have problems.

**Comment by anastely** [comment]
@satya164 I have the same problem with createMaterialTopTabNavigator?
